# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.dmvnorm_arma_mc <- function(x, mean, sigma, logd = FALSE, cores = 1L) {
    .Call('_covboost_dmvnrm_arma_mc', PACKAGE = 'covboost', x, mean, sigma, logd, cores)
}

